#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

int main() {
  int total = 0;
  int a = 1;
  int b = 1;
  int sum = 2;
  while (sum < 4e6) {
    sum = a + b;
    a = b;
    b = sum;
    if (sum % 2 == 0) { total += sum; }
  }
  printf("%d", total);
  return 0;
}
// 4613732
