### Each new term in the Fibonacci sequence is generated by adding the
### previous two terms. By starting with 1 and 2, the first 10 terms will be:
### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

### By considering the terms in the Fibonacci sequence whose values do not
### exceed four million, find the sum of the even-valued terms.

##### With Golden Ratio
import math

def fib(n):
  return(round(((1 + math.sqrt(5)) ** (n-1) - (1 - math.sqrt(5)) ** (n-1))/((2 ** (n-1)) * math.sqrt(5))))

sum(filter(lambda x: x % 2 == 0, filter(lambda x: x < 4000000, map(fib, range(50)))))
# 4613732


##### Unbounded with Generator
def fib():
    a, b = 1, 1
    while True:
        yield a
        a, b = b, a + b

def even(seq):
    for i in seq:
        if not i % 2:
            yield i

def under(seq, limit):
    for i in seq:
        if i > limit:
            break
        yield i   

sum(even(under(fib(), 4e6)))   # 4613732
