#!/bin/bash

## Each new term in the Fibonacci sequence is generated by adding the
## previous two terms. By starting with 1 and 2, the first 10 terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not
## exceed four million, find the sum of the even-valued terms.

get_fib() {
  local total=0
  local a=1
  local b=1
  local sum=2
  while [ $sum -le 4000000 ]
  do
    sum=$[$a + $b]
    a=$b
    b=$sum
    if [ $[$sum % 2] -eq 0 ]; then
      total=$[$total + $sum]
    fi
  done
  echo $total
}

get_fib
# 4613732
