### Each new term in the Fibonacci sequence is generated by adding the
### previous two terms. By starting with 1 and 2, the first 10 terms will be:
### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

### By considering the terms in the Fibonacci sequence whose values do not
### exceed four million, find the sum of the even-valued terms.

library(magrittr)
fib <- function(n) {
  l <- as.list(rep(1, n))
  for (i in seq_along(l)) {
    if (i > 2) { l[[i]] <- l[[i - 1]] + l[[i - 2]] }
  }
  l
}

fib(50) %>% Filter(function(x) x < 4000000, .) %>%
  Filter(function(x) { round(x %% 2) == 0 }, .) %>% Reduce(sum, .)  # 4613732
