### Each new term in the Fibonacci sequence is generated by adding the
### previous two terms. By starting with 1 and 2, the first 10 terms will be:
### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

### By considering the terms in the Fibonacci sequence whose values do not
### exceed four million, find the sum of the even-valued terms.

#### Using Tasks

function fib_seq()
  (a, b) = (1, 1)
  while(true)
    produce(a)
    (a, b) = (b, a + b)
  end
end

fib_gen = Task(fib_seq)
fibs = Int64[]
i = 0

while (i < 4e6)
  i = consume(fib_gen)
  push!(fibs, i)
end

println(sum(filter(x -> x % 2 == 0, fibs)))  # 4613732
