; Each new term in the Fibonacci sequence is generated by adding the
; previous two terms. By starting with 1 and 2, the first 10 terms will be:
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not
; exceed four million, find the sum of the even-valued terms.

(let [fibs (fn f [a b] (lazy-seq (cons a (f b (+ a b)))))]
  ( ->> (fibs 0 1)
        (take-while #(< % 4000000))
        (filter even?)
        (reduce +)))
; 4613732
