### Each new term in the Fibonacci sequence is generated by adding the
### previous two terms. By starting with 1 and 2, the first 10 terms will be:
### 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

### By considering the terms in the Fibonacci sequence whose values do not
### exceed four million, find the sum of the even-valued terms.

# Golden Ratio Implementation of Fibonacci
fib <- function(n) {
  n <- n + 1 # Add one because we're not starting with "1, 1, 2"
  ((1 + sqrt(5))^n - (1 - sqrt(5))^n)/(2^n * sqrt(5))
}

library(magrittr)
lapply(seq(50), fib) %>% Filter(function(x) x < 4000000, .) %>%
  Filter(function(x) { round(x %% 2) == 0 }, .) %>% Reduce(sum, .)  # 4613732


### Unbounded Version
l <- list(1, 1)
while (Reduce(sum, tail(l, 2)) < 4000000) {
  l <- append(l, Reduce(sum, tail(l, 2)))
}
Reduce(sum, Filter(function(x) round(x %% 2) == 0, l)) # 4613732
