// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

// Note: this was written independently of the Coffeescript implementation.

var total = 0;
var a = 1;
var b = 1;
var sum = 2;
while (sum < 4e6) {
  sum = a + b;
  a = b;
  b = sum;
  if (sum % 2 == 0) { total += sum; }
}
alert(total); // 4613732
